[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/ima-stats"
  to = "/.netlify/functions/ima-stats"
  status = 200

[[redirects]]
  from = "/api/sheets"
  to = "https://docs.google.com/spreadsheets/d/1CNss4CpV-kHONP4kSKrCwHvuHZ58Eo34Hsz9VL6R1Sk/export?format=csv"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
